image: docker/compose:1.25.0-rc1
variables:
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.0-dind
stages:
  - test

test:
  stage: test
  tags:
    - training-test
  script:
    - docker-compose up --build --abort-on-container-exit
