version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
  test:
    image: hvphuong98/acexis-ft-test1
    depends_on:
      - app
    volumes:
      - ./.env:/usr/src/.env
    links:
      - "app:app"
